menu:
  Home: /
  Archives: /archives

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:

# widget settings
widget: true
maxDistance: 15
sensitive: 0.01

# MathJax support
mathJax: true
